[apricot]
listen = ":8132"
disableStartupLog = true

[log]
file = "logs/apricot.log"
maxAge = 30
maxBackups = 3
maxSize = 100
maxBackup = 3
compress = true
forceColors = true

[database]
path = "apricot.sqlite"
